enum HTTPStatus {
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  OK = 200,
  INTERNAL_SERVER_ERROR = 500,
  VALIDATION_ERROR = 422,
  UNAUTHORIZED_ERROR = 401,
  PERMISSION_ERROR = 403,
}

export default HTTPStatus;
